### ISSUE TITLE
Does not work with latest update 2023.4.0

### ISSUE THREAD

**Issue by donparlor** [custom-components/sensor.avanza_stock#155]
After installing latest HA version 2023.4.0, when checking my configuration.yaml file it does not give me the green light... It simply keeps checking and checking... After removing lines of code by component I could identify that platform: avanza_stock was the culprit. After removing that line my configuration.yaml receive a green light and I could restart my system. Is it possible that platform: avanza_stock was not prepared for latest changes implemented in 2023.4.0 ??

**Comment by claha** [comment]
Didn't have time to try 2023.4.0, jumped directly to 2023.4.1 where it works fine :) so maybe update to thata d see if it works. Check the changelog maybe this can have something to do with why it does not work for u in .0 https://github.com/home-assistant/core/pull/90895 (of you are using mysql). Please let me know if it works for you, otherwise I will try and see if I get some time to test it on .0

**Comment by donparlor** [comment]
I'm presently running Home Assistant 2023.4.1 and Supervisor 2023.04.0. 
I just added back the platform: avanza_stock and I get a green light:
<img width="593" alt="Capture d’écran, le 2023-04-07 à 10 33 12" src="https://user-images.githubusercontent.com/97048708/230626614-1a29a606-e8c8-4d2d-8a8e-f5b45bc3e92d.png">

Maybe the problem was with 2023.4.0. False alarm @claha 

Thanks for jumping in
