### ISSUE TITLE
avanza stock will not load after upgrade HA to 2024.1.6 

### ISSUE THREAD

**Issue by eddysteurs** [custom-components/sensor.avanza_stock#171]
Unable to install package pyavanza==0.7.0: ERROR: Cannot install pyavanza==0.7.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
11:38:41 – (ERROR) util/package.py - message first occurred at 11:38:38 and shows up 3 times

Worked fine on 2024.1.5 but after latest upgrade fails (also after several restarts)
Works back after restore core to 2024.1.5

**Comment by claha** [comment]
Seems aiohttp was updated in 2024.1.6 so I need to make a new release of pyavanaza and then this component. Will try to get to it later today

**Comment by claha** [comment]
Should be fixed in v1.5.2, let me know if it doesn't :)

**Comment by eddysteurs** [comment]
all working fine again, great and speedy work, thanks

**Comment by yusufbogatepe** [comment]
> Should be fixed in v1.5.2, let me know if it doesn't :)

I am using on Tinkerboard rev1.2 with HA OS. It gives me this error.


Unable to install package awsiotsdk: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-312 creating build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt creating build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-fsx49y8c/awscrt_31712866fe29481f8d3a86925be9e494/setup.py", line 399, in <module> setuptools.setup( File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run self.run_command("build") File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-fsx49y8c/awscrt_31712866fe29481f8d3a86925be9e494/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-fsx49y8c/awscrt_31712866fe29481f8d3a86925be9e494/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-fsx49y8c/awscrt_31712866fe29481f8d3a86925be9e494/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-fsx49y8c/awscrt_31712866fe29481f8d3a86925be9e494/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
Unable to install package awsiotsdk: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-312 creating build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt creating build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-ygca8fz9/awscrt_c4b322c2199c4dac8d62dfa1d12dbaa1/setup.py", line 399, in <module> setuptools.setup( File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run self.run_command("build") File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-ygca8fz9/awscrt_c4b322c2199c4dac8d62dfa1d12dbaa1/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-ygca8fz9/awscrt_c4b322c2199c4dac8d62dfa1d12dbaa1/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-ygca8fz9/awscrt_c4b322c2199c4dac8d62dfa1d12dbaa1/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-ygca8fz9/awscrt_c4b322c2199c4dac8d62dfa1d12dbaa1/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
Unable to install package awsiotsdk: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-312 creating build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-312/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt creating build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-bgu6gyst/awscrt_e9bc94622d4c4eeea836677ebaa527c6/setup.py", line 399, in <module> setuptools.setup( File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run self.run_command("build") File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-bgu6gyst/awscrt_e9bc94622d4c4eeea836677ebaa527c6/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-bgu6gyst/awscrt_e9bc94622d4c4eeea836677ebaa527c6/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-bgu6gyst/awscrt_e9bc94622d4c4eeea836677ebaa527c6/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-bgu6gyst/awscrt_e9bc94622d4c4eeea836677ebaa527c6/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
Unable to install package pyavanza==0.7.0: ERROR: Cannot install pyavanza==0.7.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by claha** [comment]
avanza_stock 1.5.2 uses pyavanza 0.7.1 which has a fix for this, but your logs say you are installing pyavanza 0.7.0. So please make sure you are actually using version 1.5.2.

**Comment by yusufbogatepe** [comment]
> avanza_stock 1.5.2 uses pyavanza 0.7.1 which has a fix for this, but your logs say you are installing pyavanza 0.7.0. So please make sure you are actually using version 1.5.2.

Actually I did. I upgraded avanza_stock to 1.5.2 via hacs. but it gives me this error. I don't know why. So I restored my core to core to 2024.1.5 again.
